spring:
  application:
    name: my_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: order
        uri: lb://order-service
        predicates:
        - Path=/order/**
        order: 0

  main:
    web-application-type: reactive
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
  instance:
    lease-renewal-interval-in-seconds: 3
    # ?? 15 ??????????? eureka ???????????
    lease-expiration-duration-in-seconds: 15
